version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  web:
    build: .
    container_name: web
    ports:
      - '4000:3000'
    environment:
      - MONGODB_URL=mongodb+srv://oche:oche@prismablogr.iqsrw2b.mongodb.net/?retryWrites=true&w=majority&appName=prismablogr
    depends_on:
      - mongodb

volumes:
  mongodb_data:
